name: Build and Run Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a C compiler
      - name: Set up C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Detect and Process All Lesson Files
      - name: Build and Run Lessons
        run: |
          for file in Lesson_*.c; do
            executable=${file%.c}
            echo "Building $file..."
            gcc -o $executable $file
            echo "Running $executable..."
            ./$executable
          done

