name: Build and Test All Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a C compiler
      - name: Set up C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build and Test All Test Files
      - name: Build and Test All Lessons
        run: |
          # Check if the test and Unity directories exist
          if [ ! -d "tests" ]; then
            echo "Error: 'tests' directory not found."
            exit 1
          fi
          if [ ! -f "lib/Unity/unity.c" ]; then
            echo "Error: 'lib/Unity/unity.c' not found."
            exit 1
          fi
          
          # Loop through all test files
          for test_file in tests/test-*.c; do
            # Ensure test file exists
            if [ ! -f "$test_file" ]; then
              echo "No test files found matching 'Tests/test-*.c'."
              exit 1
            fi

            # Compile the test file
            executable=${test_file%.c}
            echo "Compiling $test_file..."
            gcc -o $executable $test_file lib/Unity/unity.c || exit 1

            # Run the test executable
            echo "Running $executable..."
            ./$executable || exit 1
          done

