name: Build and Run Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a C compiler
      - name: Set up C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Detect and Process All Lesson Files
      - name: Build and Run Lessons
        run: |
          for file in Lesson_*.c; do
            executable=${file%.c}
            echo "Building $file..."
            gcc -o $executable $file
            echo "Running $executable..."
            ./$executable
          done

# Step 4: Build and Test All Test Files
      - name: Build and Test All Lessons
        run: |
          # Loop through all test files in the tests directory
          for test_file in Tests/test-*.c; do
            # Extract the base name for the test executable
            executable=${test_file%.c}
            echo "Compiling $test_file..."
            
            # Compile the test file with Unity
            gcc -o $executable $test_file ./lib/Unity/unity.c

            
            # Run the compiled test executable
            echo "Running $executable..."
            ./$executable
          done
